// Theme metadata is shared by the renderer and the desktop window host.
export const THEMES = [
  {
    id: "monument",
    name: "鎏金殿堂",
    subtitle: "石材、黄铜与对称柱廊",
    description: "保留 V1.1 的纪念性建筑风格。",
    colors: ["#302c25", "#b99b62", "#f1ebdf"],
    background: "#eee8dc",
    architecture: true,
  },
  {
    id: "paper",
    name: "晴日纸间",
    subtitle: "留白、鼠尾草绿与柔和纸面",
    description: "轻盈、清晰，适合日常学习与长时间阅读。",
    colors: ["#edf2ed", "#52705e", "#ffffff"],
    background: "#f6f8f5",
    architecture: false,
  },
  {
    id: "midnight",
    name: "午夜星图",
    subtitle: "深蓝、雾紫与低亮度工作空间",
    description: "为晚间专注保留安静的层次。",
    colors: ["#141c2b", "#aeb7ff", "#242f43"],
    background: "#141c2b",
    architecture: false,
  },
  {
    id: "violet",
    name: "紫雾花园",
    subtitle: "鸢尾紫、月光与层叠山影",
    description: "柔和的紫色系，配以原创月夜彩绘。",
    colors: ["#e8def7", "#7656a8", "#fbf8ff"],
    background: "#f0e9fa",
    architecture: false,
  },
  {
    id: "orbital",
    name: "轨道时代",
    subtitle: "冷战年代 · 构成主义与太空图谱",
    description: "砖红、石蓝与奶油纸，取材于太空时代设计语言。",
    colors: ["#203943", "#b64732", "#f7eed8"],
    background: "#e8dfc9",
    architecture: false,
  },
  {
    id: "millennium",
    name: "千禧漫游",
    subtitle: "2000 · 液态银、青蓝与糖果粉",
    description: "铬色光泽、像素网格与透明气泡组成千禧图画。",
    colors: ["#dbe8f6", "#346ad4", "#f8fcff"],
    background: "#e8f0fb",
    architecture: false,
  },
  {
    id: "coast",
    name: "海盐来信",
    subtitle: "海岸蓝、杏色与日落剪影",
    description: "清透的海边配色，配以几何彩绘海湾。",
    colors: ["#d8eae8", "#267c88", "#fffdf5"],
    background: "#edf3ee",
    architecture: false,
  },
];
export const themeById = (id) => THEMES.find((t) => t.id === id) || THEMES[0];
