const test = require("node:test");
const assert = require("node:assert/strict");
const { harness, event } = require("./harness.cjs");
test("页面操作：门禁、演示、任务增改完成恢复、日程、专注、设置与退出", async () => {
  const h = harness();
  h.page("home");
  assert.equal(h.routes.at(-1), "/pages/login/index");
  h.page("login").demo();
  assert.equal(h.app.store.demo, true);
  let page = h.page("tasks");
  const count = page.data.tasks.length;
  page.add();
  page.field(event({ field: "title" }, "页面合成任务"));
  page.save();
  assert.equal(page.data.tasks.length, count + 1);
  const id = page.data.tasks.at(-1).id;
  page.edit(event({ id }));
  page.field(event({ field: "title" }, "已修改标题"));
  page.save();
  assert.equal(
    h.app.store.state.tasks.find((t) => t.id === id).title,
    "已修改标题",
  );
  page.toggle(event({ id }));
  assert.equal(page.data.tasks.length, count);
  page.completed();
  assert.ok(page.data.tasks.some((t) => t.id === id));
  page.edit(event({ id }));
  page.remove();
  page = h.page("profile");
  assert.ok(page.data.trash.some((t) => t.id === id));
  page.restore(event({ id, kind: "tasks" }));
  assert.ok(!page.data.trash.some((t) => t.id === id));
  page.settings();
  assert.equal(h.routes.at(-1), "/pages/settings/index");
  page = h.page("settings");
  page.theme(event({ id: "midnight" }));
  page.widget(event({ id: "priority" }, false));
  page = h.page("home");
  assert.equal(page.data.themeId, "midnight");
  assert.equal(page.data.showPriority, false);
  page = h.page("schedule");
  page.add();
  page.field(event({ field: "title" }, "页面日程"));
  page.save();
  assert.ok(page.data.items.some((item) => item.title === "页面日程"));
  page = h.page("focus");
  page.start();
  assert.equal(page.data.timerStatus, "running");
  page.pause();
  assert.equal(page.data.timerStatus, "paused");
  page.finish();
  assert.equal(page.data.timerStatus, "idle");
  page.onHide();
  page = h.page("profile");
  await page.logout();
  assert.equal(h.app.store.user, null);
  assert.equal(page.data.user, null);
  assert.equal(h.routes.at(-1), "/pages/login/index");
  assert.deepEqual(h.messages, []);
});
